### ISSUE TITLE
Truncated logo

### ISSUE THREAD

**Issue by NicolasCARPi** [Bzero/typstwriter#19]
Is the truncation of the logo SVG on purpose?

https://github.com/Bzero/typstwriter/blob/master/docs/logo/Typstwriter_Text_Compact.svg

TBH, I find it funny that for a tool aimed at producing nice looking PDF files, the logo is truncated as if there wasn't any space :laughing: 

So I'd leave it as an easter egg! ;)

**Comment by Bzero** [comment]
I am not quite sure I can follow you. Are you worried about too little distance between the circle and the "T"?

**Comment by NicolasCARPi** [comment]
Don't you see this?

![2024-07-31-182436_1034x405_scrot](https://github.com/user-attachments/assets/7aa88787-c732-4301-978f-bf2dc822a390)


![2024-07-31-182409_794x361_scrot](https://github.com/user-attachments/assets/41697151-a183-4f50-92c9-2a140cf4103b)

**Comment by Bzero** [comment]
No, actually not: 

![image](https://github.com/user-attachments/assets/081a56a1-ba33-4357-87aa-5cbf230ba252)

![image](https://github.com/user-attachments/assets/5136a150-a545-4b26-a45e-b4c7bb934299)

Thanks a lot for bringing this to my attention, that's a very peculiar issue, I'll have to investigate this!

**Comment by Bzero** [comment]
Okay, looks like a font problem to me. The SVG uses the `Crimson` font which may not be available on all systems so it falls back to another font which happens to be wider.

I think for the `README.md` this is most easily resolved by using the pre-rendered PNG instead.

**Comment by NicolasCARPi** [comment]
LGTM!

![2024-07-31-202130_1167x586_scrot](https://github.com/user-attachments/assets/ee4ed350-07f7-4835-8c4a-a20d06a345af)
