### ISSUE TITLE
Typst executable could not be found found

### ISSUE THREAD

**Issue by leo848** [Bzero/typstwriter#38]
When I run typstwriter, I get this (sic) error message. I installed the latest version of typst using `pacman -S typst'. Even specifying the absolute path in the config file, which otherwise gets respected, leads to the same error message.

I installed `typstwriter` via `pipx` on my Arch Linux system (Hyprland). Is there anything I can do to fix this?

**Comment by Bzero** [comment]
Thanks a lot for this error report, very much appreciated!

It looks as if the check to discover if typst is installed is a bit too strict and does not recognize the most recent [0.12.0](https://github.com/typst/typst/releases/tag/v0.12.0) release as a supported typst compiler. 

I will fix this shortly, for the time being you can safely ignore the error when using typst 0.12.0.

**Comment by Bzero** [comment]
Thanks for the error report, this is probably a platform specific issue though.

I will look into it.
